from typing import Optional
from pydantic import BaseModel, Field


class AllExpectations(BaseModel):
    expect_column_values_to_be_null: Optional[str] = Field(None, description="The values in the column of the table must be null")
    expect_column_values_to_not_be_null: Optional[str] = Field(None, description="The values in the column of the table must not be null")
    expect_column_values_to_not_be_null_and_column_to_not_be_empty: Optional[str] = Field(None, description="The values in the column must not be null, and the column must contain at least one non-null value.")
    expect_table_columns_to_match_set: Optional[str] = Field(None, description="The table's columns must match the specified set of columns, in any order.")
    expect_column_distinct_values_to_contain_set: Optional[str] = Field(None, description="The distinct values in the specified column must include all values in the given set.")
    expect_column_distinct_values_to_equal_set: Optional[str] = Field(None, description="The distinct values in the specified column must exactly match the given set.")
    expect_column_values_to_be_in_set: Optional[str] = Field(None, description="All values in the specified column must exist within the given set.")
    expect_column_distinct_values_to_be_in_set: Optional[str] = Field(None, description="The distinct values in the specified column must be a subset of the given set.")
    expect_column_pair_values_to_be_in_set: Optional[str] = Field(None, description="The paired values from two columns must exist as pairs in the given set.")
    expect_column_values_to_not_be_in_set: Optional[str] = Field(None, description="No values in the specified column should exist in the given set.")
    expect_column_most_common_value_to_be_in_set: Optional[str] = Field(None, description="The most common value in the specified column must exist in the given set.")
    expect_column_value_lengths_to_be_between: Optional[str] = Field(None, description="Ensure the lengths of the values in the specified column are within the given range (inclusive of the minimum and maximum length).")
    expect_column_value_lengths_to_equal: Optional[str] = Field(None, description="Ensure the lengths of all values in the specified column are equal to the given value.")
    expect_table_row_count_to_equal_other_table: Optional[str] = Field(None, description="The table row count must equal the row count of another specified table.")
    expect_table_row_count_to_equal: Optional[str] = Field(None, description="The table row count must equal the specified value.")
    expect_table_row_count_to_be_between: Optional[str] = Field(None, description="The table row count must be between the specified min and max.")
    expect_table_column_count_to_equal: Optional[str] = Field(None, description="The number of columns in the table must equal the specified value.")
    expect_table_column_count_to_be_between: Optional[str] = Field(None, description="The number of columns in the table must be between the specified min and max.")
    expect_column_values_to_not_match_regex_list: Optional[str] = Field(None, description="Column values must not match any regex in the specified list.")
    expect_column_values_to_not_match_regex: Optional[str] = Field(None, description="Column values must not match the specified regex.")
    expect_column_values_to_not_match_like_pattern_list: Optional[str] = Field(None, description="Column values must not match any SQL-like pattern in the specified list.")
    expect_column_values_to_not_match_like_pattern: Optional[str] = Field(None, description="Column values must not match the specified SQL-like pattern.")
    expect_column_values_to_match_regex_list: Optional[str] = Field(None, description="Column values must match at least one regex in the specified list.")
    expect_column_values_to_match_regex: Optional[str] = Field(None, description="Column values must match the specified regex.")
    expect_column_values_to_match_like_pattern_list: Optional[str] = Field(None, description="Column values must match at least one SQL-like pattern in the specified list.")
    expect_column_values_to_match_like_pattern: Optional[str] = Field(None, description="Column values must match the specified SQL-like pattern.")
    expect_table_columns_to_match_ordered_list: Optional[str] = Field(None, description="The table columns must match the specified ordered list.")
    expect_select_column_values_to_be_unique_within_record: Optional[str] = Field(None, description="Selected column values must be unique within each record.")
    expect_compound_columns_to_be_unique: Optional[str] = Field(None, description="The combination of values across compound columns must be unique.")
    expect_column_values_to_be_of_type: Optional[str] = Field(None, description="Column values must match the specified data type.")
    expect_column_values_to_be_in_type_list: Optional[str] = Field(None, description="Column values must match one of the data types in the specified list.")
    expect_column_values_to_match_json_schema: Optional[str] = Field(None, description="Column values must match the specified JSON schema.")
    expect_column_values_to_be_json_parseable: Optional[str] = Field(None, description="Column values must be parseable as JSON.")
    expect_column_values_to_be_dateutil_parseable: Optional[str] = Field(None, description="Column values must be parseable using dateutil.")
    expect_column_values_to_be_between: Optional[str] = Field(None, description="Column values must be within the specified range.")
    expect_column_value_z_scores_to_be_less_than: Optional[str] = Field(None, description="The Z-scores of column values must be less than the specified threshold.")
    expect_column_sum_to_be_between: Optional[str] = Field(None, description="The sum of column values must be between the specified min and max.")
    expect_column_stdev_to_be_between: Optional[str] = Field(None, description="The standard deviation of column values must be between the specified min and max.")
    expect_column_quantile_values_to_be_between: Optional[str] = Field(None, description="Quantile values of the column must fall within the specified range.")
    expect_column_proportion_of_unique_values_to_be_between: Optional[str] = Field(None, description="The proportion of unique values in the column must be between the specified min and max.")
    expect_column_values_to_be_increasing: Optional[str] = Field(None, description="Column values must be monotonically increasing.")
    expect_column_values_to_be_decreasing: Optional[str] = Field(None, description="Column values must be monotonically decreasing.")
    expect_column_values_to_be_unique: Optional[str] = Field(None, description="All column values must be unique.")
    expect_column_unique_value_count_to_be_between: Optional[str] = Field(None, description="The number of unique values in the column must be between the specified min and max.")
    expect_column_min_to_be_between: Optional[str] = Field(None, description="The minimum value in the column must be between the specified min and max.")
    expect_column_median_to_be_between: Optional[str] = Field(None, description="The median value in the column must be between the specified min and max.")
    expect_column_mean_to_be_between: Optional[str] = Field(None, description="The mean value in the column must be between the specified min and max.")
    expect_column_max_to_be_between: Optional[str] = Field(None, description="The maximum value in the column must be between the specified min and max.")
    expect_multicolumn_sum_to_equal: Optional[str] = Field(None, description="The sum of values across multiple columns must equal the specified value.")
    expect_column_pair_values_to_be_equal: Optional[str] = Field(None, description="The values in the column pair must be equal.")
    expect_column_pair_values_a_to_be_greater_than_b: Optional[str] = Field(None, description="Values in column A must be greater than values in column B.")

    