from pydantic import BaseModel, Field, model_validator
from typing import Optional, List

from request_models import connection_enum_and_metadata as conn_enum
from logging_config import dqt_logger


class DataSource(BaseModel):
    dir_path: Optional[str] = Field(None, description="Path of dir in which files need to be validated")
    file_name: Optional[str] = Field(None, description="Name of file to be validated")
    table_name: Optional[str] = Field(None, description="Name of table, data of which needs to be validated")
    schema_name: Optional[str] = Field(None, description="Schema name of the table provided")

    @model_validator(mode='before')
    def validate_data_source(cls, values):
        if values is None:
            error_msg = "data_source cannot be null or missing."
            dqt_logger.error(error_msg)
            raise ValueError(error_msg)

        dir_path = values.get('dir_path')
        file_name = values.get('file_name')
        table_name = values.get('table_name')
        schema_name = values.get('schema_name')

        if table_name:
            if (dir_path or file_name):
                error_msg = "If 'table_name' is given 'file_name' and 'dir_path' must not be specified."
                dqt_logger.error(error_msg)
                raise ValueError(error_msg)
            if not schema_name:
                error_msg = "If 'table_name is given 'schema_name' must be specified."
                dqt_logger.error(error_msg)
                raise ValueError(error_msg)
            
        if schema_name:
            if (dir_path or file_name):
                error_msg = "If 'schema_name' is given 'file_name' and 'dir_path' must not be specified."
                dqt_logger.error(error_msg)
                raise ValueError(error_msg)
            if not table_name:
                error_msg = "If 'schema_name' is given 'table_name' must be specified."
                dqt_logger.error(error_msg)
                raise ValueError(error_msg)
            
        if file_name and table_name:
                error_msg = "If 'file_name' is given 'table_name' must not be specified."
                dqt_logger.error(error_msg)
                raise ValueError(error_msg)
            
        if dir_path:
            if table_name:
                error_msg = "If 'dir_path' is given 'table_name' must not be specified."
                dqt_logger.error(error_msg)
                raise ValueError(error_msg)
            if not file_name:
                error_msg = "Specify 'file_name' when using 'dir_path'."
                dqt_logger.error(error_msg)
                raise ValueError(error_msg)

        return values


class QualityChecks(BaseModel):
    expectation_type: str = Field(str, description="Name of the check that is applied", min_length=3)
    kwargs: dict = Field(dict, description="""Contains the column on which the check is to be applied 
                                            and the arguments for the check""")


class QualityChecksFile(BaseModel):
    file_path: str = Field(str, description="The path of the file that contains the defined quality checks", min_length=5)
    master_columns: Optional[List[str]] = Field(List[str], description="The name of the columns which are being referred to", min_length=1)
    slave_columns: Optional[List[str]] = Field(List[str], description="The list of columns that contain the conditions which need to be validated", min_length=1) 
    sheet_name: Optional[str] = Field(str, description="The name of the sheet which contains the expectation rules", min_length=5)
    client_name: str = Field(str, description="The name of the client for which the custom checks are written", min_length=2)
    
    @model_validator(mode='before')
    def validate_quality_checks_file(cls, values):
        if values is None:
            error_msg = "custom quality check file cannot be null or missing."
            dqt_logger.error(error_msg)
            raise ValueError(error_msg)
        
        file_path = values.get('file_path')
        client_name = values.get('client_name')
        
        if not file_path:
            error_msg = "File path must be provided"
            dqt_logger.error(error_msg)
            raise ValueError(error_msg)

        if not client_name:
            error_msg = "Client name must be provided"
            dqt_logger.error(error_msg)
            raise ValueError(error_msg)

        return values

class SubmitJob(BaseModel):
    connection_name: str = Field(str, description="Unique connection name generated by create-connection endpoint", 
                                 min_length=36)
    data_source: DataSource
    quality_checks: Optional[List[QualityChecks]] = []
    quality_checks_file: Optional[List[QualityChecksFile]] = []
    metadata: conn_enum.Metadata
