INSERT_CONN_DETAILS_QUERY = "INSERT INTO {} VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"
INSERT_JOB_STATUS_QUERY = "INSERT INTO {} VALUES (%s, %s, %s);"
UPDATE_JOB_STATUS_QUERY = "UPDATE {} SET {} WHERE {} = %s;"
GET_LOGIN_CRED_QUERY = "SELECT {} FROM {} WHERE {} = %s;" # TODO: Test
GET_JOB_STATUS_DETAIL_QUERY = "SELECT {}, {} FROM {} WHERE {} = %s;"
READ_FOR_CONN_NAME_QUERY = "SELECT 1 FROM {} WHERE {} = %s;" # TODO: Test