INSERT_CONN_DETAILS_QUERY = "INSERT INTO {} VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"
GET_LOGIN_CRED_QUERY = "SELECT {} FROM {} WHERE {} = %s;" # TODO: Test
READ_FOR_CONN_NAME_QUERY = "SELECT 1 FROM {} WHERE {} = %s;" # TODO: Test